global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "./alert_rules.yml"

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgresql_exporter_container:9187']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter_container:9113']
  - job_name: 'django'
    static_configs:
      - targets: ['django_container:8000']


